# FROM php:8.1-apache
# RUN apt-get update && apt-get install -y \
#     libzip-dev zip unzip \
#     && docker-php-ext-install pdo pdo_mysql zip
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
# RUN a2enmod rewrite
# WORKDIR /var/www/html